version: '3.8'

services:
  web:
    build: .
    container_name: xiaozhang_blog_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    depends_on:
      - db
    networks:
      - blog_network

  db:
    image: mysql:8.0
    container_name: xiaozhang_blog_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge

volumes:
  mysql_data: 